from __future__ import annotations

import json
import logging
from collections import defaultdict
from pathlib import Path

import requests
from airflow.providers.amazon.aws.hooks.s3 import S3Hook
from airflow.providers.http.hooks.http import HttpHook
from airflow.sdk import dag, task
from common.sensors.mineru_sensor import MineruStatusSensor
from pendulum import datetime

MINERU_URL = "http://mineru-api:8000"
RAG_DATA_BUCKET = "ragfiles"
DEV_DATA = "dev_data"
DEV_DATA_MINERU = f"{DEV_DATA}/mineru_md"
DEV_DATA_UNSTRUCTURED = f"{DEV_DATA}/unstruct_jsons"
SUP_FORMATS = ["pdf/"]


def del_file(file: str | Path) -> None:
    path = Path(file)  # if isinstance(file_name, str) else file_name
    if path.exists():
        path.unlink()
        logging.info(f">>> Removed existing: {path}")


def load_to_s3(
    hook: S3Hook,
    filepath: str | list[str],
    bucket_name: str = RAG_DATA_BUCKET,
    prefix: str = DEV_DATA_MINERU,
) -> str | None:
    filepath = filepath if isinstance(filepath, list) else [filepath]
    out = ""
    try:
        for patch in filepath:
            hook.load_file(
                filename=patch,
                bucket_name=bucket_name,
                key=f"{prefix}/{patch.split('/')[-1]}",
                replace=True,
            )
            out += f"\n{patch}"
        logging.info(f">> File loaded to minio: {out}")

        return out
    except Exception as ex:
        logging.error(f">> Unknow error to load .md data to minio: {ex}")


@dag(
    dag_id="minio_to_qdrant",
    start_date=datetime(2026, 1, 1),
    schedule=None,
    catchup=False,
    tags=["data_piline"],
)

# async def fetch_file(url, session):
#     async with session.get(url) as response:
#         file = await response.read()


def minio_to_qdrant():

    @task
    def get_buckets_data(
        bucket_name_filter: str | list[str] | None = None,
    ) -> dict[str, list[str]]:
        hook = S3Hook(aws_conn_id="minio")

        try:
            buckets_data = hook.get_conn().list_buckets()
            buckets = buckets_data.get("Buckets", [])

            if bucket_name_filter:
                """
                "Buckets": [
                    {
                        "Name": "...",
                        "CreationDate": "..."
                    }, ...
                ],
                """
                target = (
                    [bucket_name_filter]
                    if isinstance(bucket_name_filter, str)
                    else bucket_name_filter
                )
                names = [b["Name"] for b in buckets if b["Name"] in target]
            else:
                names = [b["Name"] for b in buckets]

            logging.info(f"Found buckets: {names}")
            data = defaultdict(list)

            for name in names:
                prefs = hook.list_prefixes(
                    bucket_name=name,
                    delimiter="/",
                )
                data[name].extend(prefs)

            logging.info(f"Found prefixes {data}")
            return data
        except Exception as ex:
            logging.exception(ex)

    @task
    def list_files_to_process(bucket: str, prefix: str | None = None) -> list[str]:
        hook = S3Hook(aws_conn_id="minio")

        if prefix:
            return hook.list_keys(bucket_name=bucket, prefix=prefix)

        to_process = []
        for pref in hook.list_prefixes(bucket_name=bucket, delimiter="/"):
            if pref in SUP_FORMATS:
                to_process.extend(hook.list_keys(bucket_name=bucket, prefix=pref))

        return to_process

    @task
    def ckeck_mineru_health():
        hook_mineru = HttpHook(method="GET", http_conn_id="mineru")
        req = hook_mineru.run(endpoint="/health")
        return req.status_code

    # @task
    # def ckeck_unstruct_health():
    #     hook = HttpHook(method="POST", http_conn_id="unstructed")
    #     resp = hook.run(endpoint="/general/v0/general", data={})

    #     print(resp.status_code)
    #     return resp.status_code in [200, 404, 422]

    # Dynamic Task Mapping
    @task
    def submit_to_mineru(
        health_status: int,
        file_key: str,
        bucket_name: str,
    ) -> str:
        """Single def becource will be use the expand methot"""
        if health_status != 200:
            raise ValueError(f"MinerU unhealthy: {health_status}")

        hook_minio = S3Hook(aws_conn_id="minio")

        # ===== 1) Download file =====
        file_name = Path("/tmp") / file_key.split("/")[-1]
        del_file(file_name)

        file_path = hook_minio.download_file(
            key=file_key,
            bucket_name=bucket_name,
            local_path="/tmp",
            preserve_file_name=True,
            use_autogenerated_subdir=False,
        )

        logging.info(f">>> Downloaded to: {file_path}")

        # ===== 2) Submit to mineru =====
        # hook_mineru = HttpHook(method="POST", http_conn_id="mineru")
        # with open(file_path, "rb") as f:
        #     resp = hook_mineru.run(
        #         endpoint="/tasks",  # async point
        #         data={
        #             # "files": file_path,
        #             "lang_list": "cyrillic",
        #             "backend": "hybrid-auto-engine",
        #             "parse_method": "auto",
        #             "formula_enable": True,
        #             "table_enable": True,
        #             "return_md": True,
        #             "return_middle_json": False,
        #             "return_model_output": False,
        #             "return_content_list": False,
        #             "return_images": True,
        #         },
        #         files={"files": f},
        #     )
        with open(file_path, "rb") as f:
            files = {"files": f}
            data = {
                "lang_list": "cyrillic",
                "backend": "hybrid-auto-engine",
                "parse_method": "auto",
                "formula_enable": "true",
                "table_enable": "true",
                "return_md": "true",
                "return_middle_json": "false",
                "return_model_output": "false",
                "return_content_list": "false",
                "return_images": "false",
            }
            resp = requests.post("http://mineru-api:8000/tasks", files=files, data=data)

        del_file(file_path)
        return resp.json()["task_id"]

    @task
    def save_mineru_result(mineru_task_id: str) -> list[str]:
        hook_mineru = HttpHook(method="GET", http_conn_id="mineru")
        req = hook_mineru.run(endpoint=f"/tasks/{mineru_task_id}/result")
        results = req.json().get("results")

        names = []

        for name in results:
            file_path = f"/tmp/{name}.md"

            del_file(file_path)
            with open(file_path, "w", encoding="utf-8") as f:
                f.write(results[name]["md_content"])
                names.append(file_path)
                print(names)

        logging.info(f"Saved files: {'\n'.join(names)}")
        return names
        # I could add images here
        #

    @task
    def load_md_to_minio(mineru_result: list[str]):
        hook = S3Hook(aws_conn_id="minio")
        load_to_s3(hook, mineru_result)

    @task
    def unstructured_process(mineru_result: list[str]) -> list[str]:
        out = []
        for filepath in mineru_result:
            with open(filepath, "rb") as f:
                file_content = f.read()

            file_ext = Path(filepath).suffix.lower()

            if file_ext == ".md":
                data = {
                    "strategy": "fast",
                    "chunking_strategy": "by_title",
                    "max_characters": 1500,
                }
            else:
                data = {
                    "strategy": "hi_res",
                    "languages": ["rus", "eng"],
                    "infer_table_structure": True,
                }

            files = {"files": (Path(filepath).name, file_content)}
            hook = HttpHook(method="POST", http_conn_id="unstructed")
            resp = hook.run(
                endpoint="/general/v0/general",
                data=data,
                files=files,
                timeout=None,
            )
            # resp = requests.post(
            #     url="http://unstructured:8000/general/v0/general",
            #     data=data,
            #     files=files,
            #     timeout=None,
            # )

            logging.info(f">> File: {filepath} is pocessed: {resp.raise_for_status()}")

            resp_json = resp.json()
            del_file(filepath)

            new_filepath = filepath.replace(".md", ".json")
            with open(new_filepath, "w", encoding="utf-8") as f:
                json.dump(resp_json, f, ensure_ascii=False, indent=2)

            # load to minio
            hook = S3Hook(aws_conn_id="minio")
            load_to_s3(hook=hook, filepath=new_filepath, prefix=DEV_DATA_UNSTRUCTURED)

            out.append(new_filepath)

        return out

    @task
    def save_to_qdrant(unstructured_output: dict, file_key: str) -> bool:
        return True

    # ===== Grapf =====
    # ----- 1) File to process -----
    get_buckets_data()
    mineru_health = ckeck_mineru_health()
    # unstruct_health = ckeck_unstruct_health()
    files_task = list_files_to_process(bucket=RAG_DATA_BUCKET)

    # ----- 1) Dynamic Task Mapping - one branch per file -----
    mineru_task = submit_to_mineru.partial(
        bucket_name=RAG_DATA_BUCKET, health_status=mineru_health
    ).expand(
        file_key=files_task,
    )

    # ----- 2) Sensor waith -----
    # Sensor waits for completion of each task MinerU
    # (deferrable -> does not block the worker)
    mineru_wait = MineruStatusSensor.partial(
        task_id="wait_mineru",
        mineru_conn_id="mineru",
        poll_interval=60,
    ).expand(external_task_id=mineru_task)

    # ----- 3) Save the received file -----
    md_file = save_mineru_result.expand(mineru_task_id=mineru_wait.output)
    load_md_to_minio.expand(mineru_result=md_file)

    unstructured_results = unstructured_process.expand(mineru_result=md_file)

    # save_to_qdrant.expand(
    #     unstructured_output=unstructured_results,
    #     file_key=files,
    # )


minio_to_qdrant()
