from __future__ import annotations

import logging
import os  # noqa: F401
from collections import defaultdict

import requests
from airflow.providers.amazon.aws.hooks.s3 import S3Hook
from airflow.providers.http.hooks.http import HttpHook
from airflow.sdk import dag, task
from common.sensors.mineru_sensor import MineruStatusSensor
from pendulum import datetime

MINERU_URL = "http://mineru-api:8000"
RAG_DATA_BUCKET = "ragfiles"
SUP_FORMATS = ["pdf/"]


@dag(
    dag_id="minio_to_qdrant",
    start_date=datetime(2026, 1, 1),
    schedule=None,
    catchup=False,
    tags=["data_piline"],
)

# async def fetch_file(url, session):
#     async with session.get(url) as response:
#         file = await response.read()


def minio_to_qdrant():

    @task
    def get_buckets_data(
        bucket_name_filter: str | list[str] | None = None,
    ) -> dict[str, list[str]]:
        hook = S3Hook(aws_conn_id="minio")

        try:
            buckets_data = hook.get_conn().list_buckets()
            buckets = buckets_data.get("Buckets", [])

            if bucket_name_filter:
                """
                "Buckets": [
                    {
                        "Name": "...",
                        "CreationDate": "..."
                    }, ...
                ],
                """
                target = (
                    [bucket_name_filter]
                    if isinstance(bucket_name_filter, str)
                    else bucket_name_filter
                )
                names = [b["Name"] for b in buckets if b["Name"] in target]
            else:
                names = [b["Name"] for b in buckets]

            logging.info(f"Found buckets: {names}")
            data = defaultdict(list)

            for name in names:
                prefs = hook.list_prefixes(
                    bucket_name=name,
                    delimiter="/",
                )
                data[name].extend(prefs)

            logging.info(f"Found prefixes {data}")
            return data
        except Exception as ex:
            logging.exception(ex)

    @task
    def list_files_to_process(bucket: str, prefix: str | None = None) -> list[str]:
        hook = S3Hook(aws_conn_id="minio")

        if prefix:
            return hook.list_keys(bucket_name=bucket, prefix=prefix)

        to_process = []
        for pref in hook.list_prefixes(bucket_name=bucket, delimiter="/"):
            if pref in SUP_FORMATS:
                to_process.extend(hook.list_keys(bucket_name=bucket, prefix=pref))

        return to_process

    @task
    def mineru_health():
        hook_mineru = HttpHook(method="GET", http_conn_id="mineru")
        req = hook_mineru.run(endpoint="/health")
        return req.status_code

    # Dynamic Task Mapping
    @task
    def submit_to_mineru(
        health_status: int,
        file_key: str,
        bucket_name: str,
    ):
        """Single def becource will be use the expand methot"""
        if health_status != 200:
            raise ValueError(f"MinerU unhealthy: {health_status}")

        hook_minio = S3Hook(aws_conn_id="minio")

        # ===== 1) Download file =====
        file_name = f"/tmp/{file_key.split('/')[-1]}"
        if os.path.exists(file_name):
            os.unlink(file_name)
            logging.info(f">>> Removed existing: {file_name}")

        file_path = hook_minio.download_file(
            key=file_key,
            bucket_name=bucket_name,
            local_path="/tmp",
            preserve_file_name=True,
            use_autogenerated_subdir=False,
        )

        logging.info(f">>> Downloaded to: {file_path}")

        # ===== 2) Submit to mineru =====
        # hook_mineru = HttpHook(method="POST", http_conn_id="mineru")
        # with open(file_path, "rb") as f:
        #     resp = hook_mineru.run(
        #         endpoint="/tasks",  # async point
        #         data={
        #             # "files": file_path,
        #             "lang_list": "cyrillic",
        #             "backend": "hybrid-auto-engine",
        #             "parse_method": "auto",
        #             "formula_enable": True,
        #             "table_enable": True,
        #             "return_md": True,
        #             "return_middle_json": False,
        #             "return_model_output": False,
        #             "return_content_list": False,
        #             "return_images": True,
        #         },
        #         files={"files": f},
        #     )
        with open(file_path, "rb") as f:
            files = {"files": f}
            data = {
                "lang_list": "cyrillic",
                "backend": "hybrid-auto-engine",
                "parse_method": "auto",
                "formula_enable": "true",  # Строки для form-data
                "table_enable": "true",
                "return_md": "true",
                "return_middle_json": "false",
                "return_model_output": "false",
                "return_content_list": "false",
                "return_images": "true",
            }
            resp = requests.post("http://mineru-api:8000/tasks", files=files, data=data)

        os.unlink(file_path)
        return resp.json()["task_id"]

    @task
    def unstructured_process(mineru_result: dict, file_key: str) -> dict:
        return {}

    @task
    def save_to_qdrant(unstructured_output: dict, file_key: str) -> bool:
        return True

    # ===== Grapf =====
    get_buckets_data()
    mineru_health = mineru_health()
    files_task = list_files_to_process(bucket=RAG_DATA_BUCKET)

    # Dynamic Task Mapping - one branch per file
    mineru_tasks = submit_to_mineru.partial(
        bucket_name=RAG_DATA_BUCKET, health_status=mineru_health
    ).expand(
        file_key=files_task,
    )

    # Sensor waits for completion of each task MinerU (deferrable → does not block the worker)
    mineru_wait = MineruStatusSensor.partial(
        task_id="wait_mineru",
        mineru_conn_id="mineru",
        poll_interval=60,
    ).expand(external_task_id=mineru_tasks)

    print(mineru_wait.output)
    # unstructured_results = unstructured_process.expand(
    #     mineru_result=mineru_wait.output,
    #     file_key=files,
    # )

    # save_to_qdrant.expand(
    #     unstructured_output=unstructured_results,
    #     file_key=files,
    # )


minio_to_qdrant()
