apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: qdrant
  namespace: rag-dev
spec:
  serviceName: qdrant
  replicas: 1
  selector:
    matchLabels:
      app: qdrant
  template:
    metadata:
      labels:
        app: qdrant
    spec:
      containers:
        - name: qdrant
          image: qdrant/qdrant:latest
          ports:
            - containerPort: 6333
          volumeMounts:
            - name: storage
              mountPath: /qdrant/storage
      volumes:
        - name: storage
          hostPath:
            path: /mnt/c/Users/dved/Desktop/EngineeringRAG/data/qdrant
            type: DirectoryOrCreate
---
apiVersion: v1
kind: Service
metadata:
  name: qdrant
  namespace: rag-dev
spec:
  selector:
    app: qdrant
  ports:
    - port: 6333
      targetPort: 6333
